[env:dueUSB]
platform = atmelsam
board = due
framework = arduino
; extra_scripts = pre:copy_lib.py
upload_port = COM27
upload_protocol = sam-ba
upload_speed = 115200
upload_command = bossac --port=COM27 --unlock --erase --write --verify --boot --reset $SOURCE

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    sebnil/DueFlashStorage@^1.0.0
    SimpleTimer
    
monitor_port = COM12
monitor_speed = 115200

build_flags =
    -Isrc/config
    -DARDUINO_SAM_DUE
    -DVARIANT_H=\"variant/variant.h\"
    -DDEBUG_TRIGGER
